### ISSUE TITLE
Multiple pods were blocked by copy-vault-env init container finished with 137 code - OOMKilled 

### ISSUE THREAD

**Issue by natdol** [bank-vaults/vault-env#392]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-env/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Vault Env Version

1.27.1

### Installation Type

Vault Secrets Webhook

### Kubernetes Version

1.29.10

### Kubernetes Distribution/Provisioner

EKS

### Expected Behavior

The copy-vault-env finishing with code 0

### Actual Behavior

The init container  is keep being restarted but still getting :
```
copy-vault-env pod got:
terminated
Reason:Reason: OOMKilled - exit code: 137
```
which blocked the application pod to start.

### Steps To Reproduce

The situation happend after merging following Renovate Bot's MR for Vault Secrets Webhook (official helm chart)
<img width="707" alt="Screenshot 2024-12-17 at 14 48 47" src="https://github.com/user-attachments/assets/22d72023-7431-46b8-93c3-b67babfb43a7" />

We've upgraded docker image for vault-env from 1.21.6 to 1.21.7 .

### Logs

```shell
No error logs for Vault Secrets Webhook, not Vault Env init . Just the k8s event:

copy-vault-env pod got:
terminated
Reason:Reason: OOMKilled - exit code: 137
```

**Comment by csatib02** [comment]
Hey @natdol,

After the previous release, we've already observed this, and raised the default CPU and Memory requests and limits:  [see](https://github.com/bank-vaults/vault-secrets-webhook/commit/df97e40889ce4be7355910a45ece7f3be7843f08#diff-456e26c82b6846f504e70f7c8e9a0af4ea6a241626d7b59dd3522e532a33ba6d)
I took a look on the release diff between the previous version, but other than dependency updates there is nothing that we've done to the project.

For a quick solution you can raise the resource limits/requests by setting the following env-vars:

```sh
VAULT_ENV_CPU_REQUEST
VAULT_ENV_CPU_LIMIT
VAULT_ENV_MEMORY_REQUEST
VAULT_ENV_MEMORY_LIMIT
```

If this affects more users, then we can raise the default levels even more.
